#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include "../kem.h"
#include "../randombytes.h"

#define NTESTS 1 // Run only once for a clear output

// Helper function to print byte arrays in hex to a file
static void fprint_hex(FILE *f, const char* label, const uint8_t *data, size_t len) {
    fprintf(f, "%s (%zu bytes):\n", label, len);
    for (size_t i = 0; i < len; ++i) {
        fprintf(f, "%02x", data[i]);
    }
    fprintf(f, "\n\n");
}

static int test_keys(FILE *f)
{
  uint8_t pk[CRYPTO_PUBLICKEYBYTES];
  uint8_t sk[CRYPTO_SECRETKEYBYTES];
  uint8_t ct[CRYPTO_CIPHERTEXTBYTES];
  uint8_t key_a[CRYPTO_BYTES];
  uint8_t key_b[CRYPTO_BYTES];

  fprintf(f, "--- Test Case 1: Correct Key Exchange ---\n\n");

  //Alice generates a public key
  fprintf(f, "[Alice] Generating key pair...\n");
  crypto_kem_keypair(pk, sk);
  fprint_hex(f, "Public Key (pk)", pk, CRYPTO_PUBLICKEYBYTES);
  fprint_hex(f, "Secret Key (sk)", sk, CRYPTO_SECRETKEYBYTES);

  //Bob derives a secret key and creates a response
  fprintf(f, "[Bob] Encapsulating a shared secret using Alice's public key...\n");
  crypto_kem_enc(ct, key_b, pk);
  fprint_hex(f, "Ciphertext (ct)", ct, CRYPTO_CIPHERTEXTBYTES);
  fprint_hex(f, "Shared Secret (key_b) generated by Bob", key_b, CRYPTO_BYTES);

  //Alice uses Bobs response to get her shared key
  fprintf(f, "[Alice] Decapsulating the ciphertext using her secret key...\n");
  crypto_kem_dec(key_a, ct, sk);
  fprint_hex(f, "Shared Secret (key_a) derived by Alice", key_a, CRYPTO_BYTES);

  if(memcmp(key_a, key_b, CRYPTO_BYTES)) {
    fprintf(f, "ERROR: Shared secrets do not match!\n\n");
    return 1;
  } else {
    fprintf(f, "SUCCESS: Shared secrets match.\n\n");
  }

  return 0;
}

static int test_invalid_sk_a(FILE *f)
{
  uint8_t pk[CRYPTO_PUBLICKEYBYTES];
  uint8_t sk[CRYPTO_SECRETKEYBYTES];
  uint8_t ct[CRYPTO_CIPHERTEXTBYTES];
  uint8_t key_a[CRYPTO_BYTES];
  uint8_t key_b[CRYPTO_BYTES];

  fprintf(f, "--- Test Case 2: Decapsulation with Invalid Secret Key ---\n\n");

  //Alice generates a public key
  crypto_kem_keypair(pk, sk);
  fprintf(f, "[Step 1] Key pair generated.\n");

  //Bob derives a secret key and creates a response
  crypto_kem_enc(ct, key_b, pk);
  fprintf(f, "[Step 2] Bob encapsulated a secret.\n");

  //Replace secret key with random values
  fprintf(f, "[Step 3] Corrupting Alice's secret key with random data...\n");
  randombytes(sk, CRYPTO_SECRETKEYBYTES);

  //Alice uses Bobs response to get her shared key
  fprintf(f, "[Step 4] Alice attempts to decapsulate with the wrong secret key...\n");
  crypto_kem_dec(key_a, ct, sk);

  if(!memcmp(key_a, key_b, CRYPTO_BYTES)) {
    fprintf(f, "ERROR: Shared secrets match, which should not happen with an invalid secret key!\n\n");
    return 1;
  } else {
    fprintf(f, "SUCCESS: Shared secrets do not match, as expected.\n\n");
  }

  return 0;
}

static int test_invalid_ciphertext(FILE *f)
{
  uint8_t pk[CRYPTO_PUBLICKEYBYTES];
  uint8_t sk[CRYPTO_SECRETKEYBYTES];
  uint8_t ct[CRYPTO_CIPHERTEXTBYTES];
  uint8_t key_a[CRYPTO_BYTES];
  uint8_t key_b[CRYPTO_BYTES];
  uint8_t b;
  size_t pos;

  fprintf(f, "--- Test Case 3: Decapsulation with Invalid Ciphertext ---\n\n");

  do {
    randombytes(&b, sizeof(uint8_t));
  } while(!b);
  randombytes((uint8_t *)&pos, sizeof(size_t));

  //Alice generates a public key
  crypto_kem_keypair(pk, sk);
  fprintf(f, "[Step 1] Key pair generated.\n");

  //Bob derives a secret key and creates a response
  crypto_kem_enc(ct, key_b, pk);
  fprintf(f, "[Step 2] Bob encapsulated a secret.\n");

  //Change some byte in the ciphertext (i.e., encapsulated key)
  fprintf(f, "[Step 3] Corrupting one byte in the ciphertext...\n");
  ct[pos % CRYPTO_CIPHERTEXTBYTES] ^= b;

  //Alice uses Bobs response to get her shared key
  fprintf(f, "[Step 4] Alice attempts to decapsulate the corrupted ciphertext...\n");
  crypto_kem_dec(key_a, ct, sk);

  if(!memcmp(key_a, key_b, CRYPTO_BYTES)) {
    fprintf(f, "ERROR: Shared secrets match, which should not happen with an invalid ciphertext!\n\n");
    return 1;
  } else {
    fprintf(f, "SUCCESS: Shared secrets do not match, as expected.\n\n");
  }

  return 0;
}

int main(void)
{
  unsigned int i;
  int r;
  FILE *f_out;

  f_out = fopen("output.txt", "w");
  if (f_out == NULL) {
      printf("ERROR: Could not open output.txt for writing.\n");
      return 1;
  }

  fprintf(f_out, "Kyber KEM Test Suite\n");
  fprintf(f_out, "====================\n\n");
  fprintf(f_out, "Running %d test cycle(s).\n\n", NTESTS);

  for(i=0;i<NTESTS;i++) {
    fprintf(f_out, "----------- Cycle %d -----------\n", i + 1);
    r  = test_keys(f_out);
    r |= test_invalid_sk_a(f_out);
    r |= test_invalid_ciphertext(f_out);
    if(r) {
      fprintf(f_out, "\nCycle %d FAILED.\n", i + 1);
      printf("A test failed. Check output.txt for details.\n");
      fclose(f_out);
      return 1;
    }
    fprintf(f_out, "----------- Cycle %d PASSED -----------\n\n", i + 1);
  }

  fprintf(f_out, "\nAll tests passed successfully.\n\n");

  fprintf(f_out, "--- Algorithm Parameters ---\n");
  fprintf(f_out, "CRYPTO_SECRETKEYBYTES:  %d\n",CRYPTO_SECRETKEYBYTES);
  fprintf(f_out, "CRYPTO_PUBLICKEYBYTES:  %d\n",CRYPTO_PUBLICKEYBYTES);
  fprintf(f_out, "CRYPTO_CIPHERTEXTBYTES: %d\n",CRYPTO_CIPHERTEXTBYTES);
  fprintf(f_out, "CRYPTO_BYTES (shared secret size): %d\n",CRYPTO_BYTES);

  fclose(f_out);
  printf("Successfully ran tests. Check output.txt for details.\n");

  return 0;
}
